service: awsnode
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - Effetc: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  hello:
    handler: handler.hello
    environment:
      bucket: serverless
    events:
      - s3:
          bucket: serverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - sufix: .jpg
      - s3:
          bucket: serverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - sufix: .png